name: entrega continua
on: ["push","pull_request"]

jobs:
    entrega-py:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: verifica codigo
          uses: actions/checkout@v6
        - name: using python
          uses: actions/setup-python@v6
          with:
            python-version: "3.13"
        - name: adicionar requeriment
          run: pip install -r requirements.txt
        - name: 
        - name: roda testes
          run: pytest 
          env:
            DB_USER: test
            PASSWORD: test
            DB_HOST: localhost
            DB_NAME: test
            SCHEMA: public
            
